import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html style={{ padding: '0px', margin: '0px' }}>
      <body
        className={inter.className}
        style={{ padding: '0px', margin: '0px'
       }}
      >
        {children}
      </body>
    </html>
  )
}
